
# language is used to specify the language that is being used in the project
#  which is used to determine the default paths to watch for changes
# and the default command to run the server.
# Possible values are "typescript" and "python"
language = "typescript"

[build]
# command and args are used to specify the command to build the server after changes
# These are the default values for typescript:
# command = "npm"
# args = ["run", "build"]

[run]
# command and args are used to specify the command to run the server
# during development after it has been rebuilt

# command = "node"
# args = ["build/index.js"]

# watch configurations are used to specify the files and directories to watch for changes
# when hot reloading the server during development
[watch]
# default_paths are the paths that are watched by default
# and are defined by the language that is being used.
# You can override the default paths by specifying them here.
# These are the paths that are watched by default for typescript:
# default_paths = ["src", "package.json", "package-lock.json"]
# and these are the paths that are watched by default for python:
# default_paths = ["src", "pyproject.toml"]

# extra_paths are the paths that are watched in addition to the default paths.
# You can use it to add more paths to watch for changes besides the default paths.
# extra_paths = [
    # "synf.toml"
# ]